services:
  user_service:
    build: ./user_service
    container_name: user_service

  order_service:
    build: ./order_service
    container_name: order_service

  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - "5000:5000"

    depends_on:
     - user_service
     - order_service
